### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by n3roGit** [liv-in-sky/battery-iobroker-vis-table#2]
Das Encoding scheint beim Upload kaputt gegangen zu sein.

Bep:

`
//HIER DIE SPALTEN ANZAHL DEFINIEREN - jede Spalte einen Wert - in diesem Beispiel sind es 3
var htmlFeld1='Gerät';      var Feld1lAlign="left";                     // �berschrift Tabellen Spalte1 und  Ausrichtung left,right or center
var htmlFeld2='Batterie';        var Feld2lAlign="center";                      // �berschrift Tabellen Spalte2 und  Ausrichtung left,right or center
var htmlFeld3='Status';         var Feld3lAlign="center";                    // �berschrift Tabellen Spalte3 und  Ausrichtung left,right or center
//-----------------------------------
 `

**Comment by liv-in-sky** [comment]
ist geändert
